name: pythia-intake-esm-tutorial
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - mamba
  - intake-esm
  - matplotlib
  - xarray
  - dask
  - distributed
  - cf-time
  - pip
  - pip:
    - s3fs
